### PR TITLE
Adds option to place 'note' area in gmail sidebar

### PR DESCRIPTION
**Pull request by janeklb**
First of all, awesome plugin - thanks!

This PR allows you to put the "note area" in the gmail sidebar, which tends to have a lot more free space.

### CODE REVIEW

**Comment by walty8** [comment]
hi, thanks a lot for your work! 

I am in the middle of a major feature now, would merge the request once my current work is done.

thanks

**Comment by janeklb** [comment]
I've rebased this off the latest master - hopefully that'll make your job a bit easier :) No rush though, and happy to rebase / prepare a fresh branch once you're work is done - just let me know.

**Comment by walty8** [comment]
hi, just briefly tested the patch. 

normal view + side top: works fine
normal view + side bottom: text area disappeared
split view + side top: text area shown at top instead of side
split view + side bottom: text area disappeared

Not sure if it's because I updated the master branch, could you help check pls?

thanks.

**Comment by janeklb** [comment]
Hi @walty8, im unclear as to what you mean by normal view vs split view?

**Comment by janeklb** [comment]
Ah, is this about the "Preview Pane" labs setting? If so, I did not do anything to support that at all..

**Comment by janeklb** [comment]
I do see the issue with the 'sidebar bottom' setting not working though- I'll try to address that

**Comment by janeklb** [comment]
Ok, please try again (for the 'normal' view)

**Pull request merged**
